databases:
  - name: pedido-db
    plan: free
    databaseName: pedido
    user: pedido_user

services:
  - type: web
    name: pedido-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      # Variable URL Ãºnica para conectar a la BD
      - key: DATABASE_URL
        fromDatabase:
          name: pedido-db
          property: internalDatabaseUrl
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod