services:
  - type: web
    name: pedido-api
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/pedido-0.0.1-SNAPSHOT.jar

databases:
  - name: pedido-db
    databaseName: dbpedidos
    user: postgres_user
    plan: free
