services:
  - type: web
    name: pedido-api
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/pedido-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Dserver.port=8080

databases:
  - name: pedido-db
    databaseName: dbpedidos
    user: postgres
    plan: free
