services:
  - type: web
    name: pedido-api
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: pedido-db
          property: connectionString

databases:
  - name: pedido-db
    ipAllowList: []
    plan: free
