databases:
  - name: pedido-db
    plan: free
    databaseName: pedido
    user: pedido_user

services:
  - type: web
    name: pedido-api
    plan: free
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/pedido-0.0.1-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pedido-db
          property: connectionString
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod