services:
  - type: web
    name: pedido-api
    runtime: docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: pedido-db
    databaseName: dbpedidos
    user: pedido_user
    plan: free
